-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:06272de86ff78689ff2d9fbb61a085e0$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "endless-l.png",
				spriteColorRect = { x = 0, y = 0, width = 173, height = 115 },
				textureRect = { x = 841, y = 119, width = 173, height = 115 },
				spriteSourceSize = { width = 173, height = 115 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "endless.png",
				spriteColorRect = { x = 0, y = 0, width = 427, height = 83 },
				textureRect = { x = 431, y = 447, width = 427, height = 83 },
				spriteSourceSize = { width = 427, height = 83 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "play-l.png",
				spriteColorRect = { x = 0, y = 0, width = 173, height = 115 },
				textureRect = { x = 841, y = 2, width = 173, height = 115 },
				spriteSourceSize = { width = 173, height = 115 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "play.png",
				spriteColorRect = { x = 0, y = 0, width = 427, height = 83 },
				textureRect = { x = 2, y = 431, width = 427, height = 83 },
				spriteSourceSize = { width = 427, height = 83 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rank.png",
				spriteColorRect = { x = 0, y = 0, width = 212, height = 221 },
				textureRect = { x = 627, y = 2, width = 212, height = 221 },
				spriteSourceSize = { width = 212, height = 221 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shop.png",
				spriteColorRect = { x = 0, y = 0, width = 212, height = 220 },
				textureRect = { x = 2, y = 516, width = 212, height = 220 },
				spriteSourceSize = { width = 212, height = 220 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "task.png",
				spriteColorRect = { x = 0, y = 0, width = 212, height = 220 },
				textureRect = { x = 627, y = 225, width = 212, height = 220 },
				spriteSourceSize = { width = 212, height = 220 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "title.png",
				spriteColorRect = { x = 0, y = 0, width = 623, height = 427 },
				textureRect = { x = 2, y = 2, width = 623, height = 427 },
				spriteSourceSize = { width = 623, height = 427 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

