-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:c99825be23d7bd0a41cf9bb3c8158d62$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "company.png",
				spriteColorRect = { x = 0, y = 0, width = 182, height = 182 },
				textureRect = { x = 2, y = 2, width = 182, height = 182 },
				spriteSourceSize = { width = 182, height = 182 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "progress.png",
				spriteColorRect = { x = 2, y = 0, width = 82, height = 83 },
				textureRect = { x = 2, y = 186, width = 82, height = 83 },
				spriteSourceSize = { width = 86, height = 85 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

