-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:c085666bc53741f391a9ac84603f16dd$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "back.png",
				spriteColorRect = { x = 4, y = 4, width = 144, height = 38 },
				textureRect = { x = 777, y = 981, width = 144, height = 38 },
				spriteSourceSize = { width = 152, height = 46 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "board.png",
				spriteColorRect = { x = 0, y = 6, width = 800, height = 810 },
				textureRect = { x = 2, y = 2, width = 800, height = 810 },
				spriteSourceSize = { width = 800, height = 816 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "easy.png",
				spriteColorRect = { x = 20, y = 0, width = 143, height = 97 },
				textureRect = { x = 632, y = 913, width = 143, height = 97 },
				spriteSourceSize = { width = 163, height = 97 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "el-green.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 206, y = 917, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "el-red.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 104, y = 917, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "el-yellow.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 2, y = 917, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "eraser1.png",
				spriteColorRect = { x = 0, y = 0, width = 78, height = 80 },
				textureRect = { x = 804, y = 696, width = 78, height = 80 },
				spriteSourceSize = { width = 80, height = 80 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "eraser3.png",
				spriteColorRect = { x = 0, y = 0, width = 78, height = 80 },
				textureRect = { x = 777, y = 899, width = 78, height = 80 },
				spriteSourceSize = { width = 80, height = 80 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "expert.png",
				spriteColorRect = { x = 0, y = 0, width = 163, height = 97 },
				textureRect = { x = 308, y = 917, width = 163, height = 97 },
				spriteSourceSize = { width = 163, height = 97 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hard.png",
				spriteColorRect = { x = 6, y = 0, width = 157, height = 97 },
				textureRect = { x = 473, y = 917, width = 157, height = 97 },
				spriteSourceSize = { width = 163, height = 97 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "help.png",
				spriteColorRect = { x = 14, y = 14, width = 64, height = 64 },
				textureRect = { x = 966, y = 839, width = 64, height = 64 },
				spriteSourceSize = { width = 94, height = 94 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "help.png",
				spriteColorRect = { x = 20, y = 1, width = 31, height = 69 },
				textureRect = { x = 914, y = 770, width = 31, height = 69 },
				spriteSourceSize = { width = 73, height = 73 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "m-book.png",
				spriteColorRect = { x = 0, y = 0, width = 645, height = 692 },
				textureRect = { x = 804, y = 2, width = 645, height = 692 },
				spriteSourceSize = { width = 645, height = 692 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "no-bg.png",
				spriteColorRect = { x = 6, y = 6, width = 72, height = 72 },
				textureRect = { x = 884, y = 696, width = 72, height = 72 },
				spriteSourceSize = { width = 84, height = 84 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "normal.png",
				spriteColorRect = { x = 12, y = 0, width = 151, height = 97 },
				textureRect = { x = 559, y = 814, width = 151, height = 97 },
				spriteSourceSize = { width = 163, height = 97 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "option.png",
				spriteColorRect = { x = 0, y = 0, width = 73, height = 73 },
				textureRect = { x = 839, y = 778, width = 73, height = 73 },
				spriteSourceSize = { width = 73, height = 73 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pause.png",
				spriteColorRect = { x = 22, y = 19, width = 34, height = 42 },
				textureRect = { x = 839, y = 853, width = 34, height = 42 },
				spriteSourceSize = { width = 80, height = 80 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "pen.png",
				spriteColorRect = { x = 1, y = 2, width = 125, height = 83 },
				textureRect = { x = 712, y = 814, width = 125, height = 83 },
				spriteSourceSize = { width = 129, height = 87 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "pencil.png",
				spriteColorRect = { x = 10, y = 8, width = 107, height = 69 },
				textureRect = { x = 857, y = 897, width = 107, height = 69 },
				spriteSourceSize = { width = 129, height = 87 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rank.png",
				spriteColorRect = { x = 4, y = 3, width = 65, height = 67 },
				textureRect = { x = 947, y = 770, width = 65, height = 67 },
				spriteSourceSize = { width = 73, height = 73 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "select.png",
				spriteColorRect = { x = 0, y = 0, width = 46, height = 46 },
				textureRect = { x = 923, y = 968, width = 46, height = 46 },
				spriteSourceSize = { width = 46, height = 46 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tips.png",
				spriteColorRect = { x = 4, y = 4, width = 79, height = 66 },
				textureRect = { x = 958, y = 696, width = 79, height = 66 },
				spriteSourceSize = { width = 87, height = 74 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "title.png",
				spriteColorRect = { x = 5, y = 3, width = 555, height = 101 },
				textureRect = { x = 2, y = 814, width = 555, height = 101 },
				spriteSourceSize = { width = 565, height = 109 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

